In [1]:
import numpy as np
import pandas as pd

In [2]:
movies = pd.read_csv('tmdb_5000_movies.csv')
credits = pd.read_csv('tmdb_5000_credits.csv')

In [3]:
movies.head(1)

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,production_countries,release_date,revenue,runtime,spoken_languages,status,tagline,title,vote_average,vote_count
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2009-12-10,2787965087,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800

In [4]:
credits.head(1)

,movie_id,title,cast,crew
0,19995,Avatar,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."

In [5]:
movies = movies.merge(credits, on='title')

In [6]:
movies['original_language'].value_counts()

en    4510
fr      70
es      32
zh      27
de      27
hi      19
ja      16
it      14
ko      12
cn      12
ru      11
pt       9
da       7
sv       5
nl       4
fa       4
th       3
he       3
ta       2
cs       2
ro       2
id       2
ar       2
vi       1
sl       1
ps       1
no       1
ky       1
hu       1
pl       1
af       1
nb       1
tr       1
is       1
xx       1
te       1
el       1
Name: original_language, dtype: int64

In [7]:
#genres
#id
#keywords
#title
#overview
#cast
#crew

movies = movies[['movie_id', 'title', 'overview', 'genres', 'keywords', 'cast', 'crew']]

In [8]:
movies.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 4809 entries, 0 to 4808
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   movie_id  4809 non-null   int64
 1   title     4809 non-null   object
 2   overview  4806 non-null   object
 3   genres    4809 non-null   object
 4   keywords  4809 non-null   object
 5   cast      4809 non-null   object
 6   crew      4809 non-null   object
dtypes: int64(1), object(6)
memory usage: 300.6+ KB

In [9]:
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...","[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...","[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,A cryptic message from Bond’s past sends him o...,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...","[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...","[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...","[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"John Carter is a war-weary, former military ca...","[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 818, ""name"": ""based on novel""}, {""id"":...","[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [10]:
movies['overview'][0]

'In the 22nd century, a paraplegic Marine is dispatched to the moon Pandora on a unique mission, but becomes torn between following orders and protecting an alien civilization.'

In [11]:
movies.isnull().sum()

movie_id    0
title       0
overview    3
genres      0
keywords    0
cast        0
crew        0
dtype: int64

In [12]:
movies.dropna(inplace=True)

In [13]:
movies.duplicated().sum()

0

In [14]:
movies.iloc[0].genres

'[{"id": 28, "name": "Action"}, {"id": 12, "name": "Adventure"}, {"id": 14, "name": "Fantasy"}, {"id": 878, "name": "Science Fiction"}]'

In [15]:
import ast

def convert(obj):
    L = []
    for i in ast.literal_eval(obj):
        L.append(i['name'])
    return L

In [16]:
movies['genres'] = movies['genres'].apply(convert)

In [17]:
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[Action, Adventure, Fantasy, Science Fiction]","[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[Adventure, Fantasy, Action]","[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...","[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,A cryptic message from Bond’s past sends him o...,"[Action, Adventure, Crime]","[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...","[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,"[Action, Crime, Drama, Thriller]","[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...","[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"John Carter is a war-weary, former military ca...","[Action, Adventure, Science Fiction]","[{""id"": 818, ""name"": ""based on novel""}, {""id"":...","[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [18]:
movies['keywords'] = movies['keywords'].apply(convert)

In [19]:
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[Adventure, Fantasy, Action]","[ocean, drug abuse, exotic island, east india ...","[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,A cryptic message from Bond’s past sends him o...,"[Action, Adventure, Crime]","[spy, based on novel, secret agent, sequel, mi...","[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,"[Action, Crime, Drama, Thriller]","[dc comics, crime fighter, terrorist, secret i...","[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"John Carter is a war-weary, former military ca...","[Action, Adventure, Science Fiction]","[based on novel, mars, medallion, space travel...","[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [20]:
def convert3(obj):
    L = []
    counter = 0
    for i in ast.literal_eval(obj):
        if(counter!=3):
            L.append(i['name'])
            counter+=1
        else:
            break
    return L

In [21]:
movies['cast'] = movies['cast'].apply(convert3)

In [22]:
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...","[Sam Worthington, Zoe Saldana, Sigourney Weaver]","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[Adventure, Fantasy, Action]","[ocean, drug abuse, exotic island, east india ...","[Johnny Depp, Orlando Bloom, Keira Knightley]","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,A cryptic message from Bond’s past sends him o...,"[Action, Adventure, Crime]","[spy, based on novel, secret agent, sequel, mi...","[Daniel Craig, Christoph Waltz, Léa Seydoux]","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,"[Action, Crime, Drama, Thriller]","[dc comics, crime fighter, terrorist, secret i...","[Christian Bale, Michael Caine, Gary Oldman]","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"John Carter is a war-weary, former military ca...","[Action, Adventure, Science Fiction]","[based on novel, mars, medallion, space travel...","[Taylor Kitsch, Lynn Collins, Samantha Morton]","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [23]:
def fetch_director(obj):
    L = []
    for i in ast.literal_eval(obj):
        if(i['job']=='Director'):
            L.append(i['name'])
            break
    return L

In [24]:
movies['crew'] = movies['crew'].apply(fetch_director)

In [25]:
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...","[Sam Worthington, Zoe Saldana, Sigourney Weaver]",[James Cameron]
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[Adventure, Fantasy, Action]","[ocean, drug abuse, exotic island, east india ...","[Johnny Depp, Orlando Bloom, Keira Knightley]",[Gore Verbinski]
2,206647,Spectre,A cryptic message from Bond’s past sends him o...,"[Action, Adventure, Crime]","[spy, based on novel, secret agent, sequel, mi...","[Daniel Craig, Christoph Waltz, Léa Seydoux]",[Sam Mendes]
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,"[Action, Crime, Drama, Thriller]","[dc comics, crime fighter, terrorist, secret i...","[Christian Bale, Michael Caine, Gary Oldman]",[Christopher Nolan]
4,49529,John Carter,"John Carter is a war-weary, former military ca...","[Action, Adventure, Science Fiction]","[based on novel, mars, medallion, space travel...","[Taylor Kitsch, Lynn Collins, Samantha Morton]",[Andrew Stanton]

In [26]:
movies['overview'][0]

'In the 22nd century, a paraplegic Marine is dispatched to the moon Pandora on a unique mission, but becomes torn between following orders and protecting an alien civilization.'

In [27]:
movies['overview'] = movies['overview'].apply(lambda x:x.split())

In [28]:
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin...","[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...","[Sam Worthington, Zoe Saldana, Sigourney Weaver]",[James Cameron]
1,285,Pirates of the Caribbean: At World's End,"[Captain, Barbossa,, long, believed, to, be, d...","[Adventure, Fantasy, Action]","[ocean, drug abuse, exotic island, east india ...","[Johnny Depp, Orlando Bloom, Keira Knightley]",[Gore Verbinski]
2,206647,Spectre,"[A, cryptic, message, from, Bond’s, past, send...","[Action, Adventure, Crime]","[spy, based on novel, secret agent, sequel, mi...","[Daniel Craig, Christoph Waltz, Léa Seydoux]",[Sam Mendes]
3,49026,The Dark Knight Rises,"[Following, the, death, of, District, Attorney...","[Action, Crime, Drama, Thriller]","[dc comics, crime fighter, terrorist, secret i...","[Christian Bale, Michael Caine, Gary Oldman]",[Christopher Nolan]
4,49529,John Carter,"[John, Carter, is, a, war-weary,, former, mili...","[Action, Adventure, Science Fiction]","[based on novel, mars, medallion, space travel...","[Taylor Kitsch, Lynn Collins, Samantha Morton]",[Andrew Stanton]

In [29]:
movies['genres'] = movies['genres'].apply(lambda x:[i.replace(" ","") for i in x])
movies['keywords'] = movies['keywords'].apply(lambda x:[i.replace(" ","") for i in x])
movies['cast'] = movies['cast'].apply(lambda x:[i.replace(" ","") for i in x])
movies['crew'] = movies['crew'].apply(lambda x:[i.replace(" ","") for i in x])

In [30]:
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin...","[Action, Adventure, Fantasy, ScienceFiction]","[cultureclash, future, spacewar, spacecolony, ...","[SamWorthington, ZoeSaldana, SigourneyWeaver]",[JamesCameron]
1,285,Pirates of the Caribbean: At World's End,"[Captain, Barbossa,, long, believed, to, be, d...","[Adventure, Fantasy, Action]","[ocean, drugabuse, exoticisland, eastindiatrad...","[JohnnyDepp, OrlandoBloom, KeiraKnightley]",[GoreVerbinski]
2,206647,Spectre,"[A, cryptic, message, from, Bond’s, past, send...","[Action, Adventure, Crime]","[spy, basedonnovel, secretagent, sequel, mi6, ...","[DanielCraig, ChristophWaltz, LéaSeydoux]",[SamMendes]
3,49026,The Dark Knight Rises,"[Following, the, death, of, District, Attorney...","[Action, Crime, Drama, Thriller]","[dccomics, crimefighter, terrorist, secretiden...","[ChristianBale, MichaelCaine, GaryOldman]",[ChristopherNolan]
4,49529,John Carter,"[John, Carter, is, a, war-weary,, former, mili...","[Action, Adventure, ScienceFiction]","[basedonnovel, mars, medallion, spacetravel, p...","[TaylorKitsch, LynnCollins, SamanthaMorton]",[AndrewStanton]

In [31]:
movies['tags'] = movies['keywords']

In [32]:
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew,tags
0,19995,Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin...","[Action, Adventure, Fantasy, ScienceFiction]","[cultureclash, future, spacewar, spacecolony, ...","[SamWorthington, ZoeSaldana, SigourneyWeaver]",[JamesCameron],"[cultureclash, future, spacewar, spacecolony, ..."
1,285,Pirates of the Caribbean: At World's End,"[Captain, Barbossa,, long, believed, to, be, d...","[Adventure, Fantasy, Action]","[ocean, drugabuse, exoticisland, eastindiatrad...","[JohnnyDepp, OrlandoBloom, KeiraKnightley]",[GoreVerbinski],"[ocean, drugabuse, exoticisland, eastindiatrad..."
2,206647,Spectre,"[A, cryptic, message, from, Bond’s, past, send...","[Action, Adventure, Crime]","[spy, basedonnovel, secretagent, sequel, mi6, ...","[DanielCraig, ChristophWaltz, LéaSeydoux]",[SamMendes],"[spy, basedonnovel, secretagent, sequel, mi6, ..."
3,49026,The Dark Knight Rises,"[Following, the, death, of, District, Attorney...","[Action, Crime, Drama, Thriller]","[dccomics, crimefighter, terrorist, secretiden...","[ChristianBale, MichaelCaine, GaryOldman]",[ChristopherNolan],"[dccomics, crimefighter, terrorist, secretiden..."
4,49529,John Carter,"[John, Carter, is, a, war-weary,, former, mili...","[Action, Adventure, ScienceFiction]","[basedonnovel, mars, medallion, spacetravel, p...","[TaylorKitsch, LynnCollins, SamanthaMorton]",[AndrewStanton],"[basedonnovel, mars, medallion, spacetravel, p..."

In [33]:
movies['tags'][0]

['cultureclash',
 'future',
 'spacewar',
 'spacecolony',
 'society',
 'spacetravel',
 'futuristic',
 'romance',
 'space',
 'alien',
 'tribe',
 'alienplanet',
 'cgi',
 'marine',
 'soldier',
 'battle',
 'loveaffair',
 'antiwar',
 'powerrelations',
 'mindandsoul',
 '3d']

In [34]:
new_df = movies[['movie_id','title','tags']]

In [35]:
new_df['tags'] = new_df['tags'].apply(lambda x:" ".join(x))

C:\Users\SARVESH GANGU\AppData\Local\Temp\ipykernel_19020\3089450492.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['tags'] = new_df['tags'].apply(lambda x:" ".join(x))

In [36]:
new_df.head()

,movie_id,title,tags
0,19995,Avatar,cultureclash future spacewar spacecolony socie...
1,285,Pirates of the Caribbean: At World's End,ocean drugabuse exoticisland eastindiatradingc...
2,206647,Spectre,spy basedonnovel secretagent sequel mi6 britis...
3,49026,The Dark Knight Rises,dccomics crimefighter terrorist secretidentity...
4,49529,John Carter,basedonnovel mars medallion spacetravel prince...

In [37]:
new_df['tags'][0]

'cultureclash future spacewar spacecolony society spacetravel futuristic romance space alien tribe alienplanet cgi marine soldier battle loveaffair antiwar powerrelations mindandsoul 3d'

In [38]:
new_df['tags'] = new_df['tags'].apply(lambda x:x.lower())

C:\Users\SARVESH GANGU\AppData\Local\Temp\ipykernel_19020\3214958533.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['tags'] = new_df['tags'].apply(lambda x:x.lower())

In [39]:
new_df.head()

,movie_id,title,tags
0,19995,Avatar,cultureclash future spacewar spacecolony socie...
1,285,Pirates of the Caribbean: At World's End,ocean drugabuse exoticisland eastindiatradingc...
2,206647,Spectre,spy basedonnovel secretagent sequel mi6 britis...
3,49026,The Dark Knight Rises,dccomics crimefighter terrorist secretidentity...
4,49529,John Carter,basedonnovel mars medallion spacetravel prince...

In [40]:
import nltk

In [41]:
from nltk.stem.porter import PorterStemmer

ps = PorterStemmer()

In [42]:
def stem(text):
    y = []
    
    for i in text.split():
        y.append(ps.stem(i))
        
    return " ".join(y)

In [43]:
new_df['tags'] = new_df['tags'].apply(stem)

C:\Users\SARVESH GANGU\AppData\Local\Temp\ipykernel_19020\3213734980.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['tags'] = new_df['tags'].apply(stem)

In [44]:
new_df['tags'][0]

'cultureclash futur spacewar spacecoloni societi spacetravel futurist romanc space alien tribe alienplanet cgi marin soldier battl loveaffair antiwar powerrel mindandsoul 3d'

In [45]:
new_df['tags'][1]

"ocean drugabus exoticisland eastindiatradingcompani loveofone'slif traitor shipwreck strongwoman ship allianc calypso afterlif fighter pirat swashbuckl aftercreditssting"

In [46]:
from sklearn.feature_extraction.text import CountVectorizer

cv = CountVectorizer(max_features=5000, stop_words='english')

In [47]:
vectors = cv.fit_transform(new_df['tags']).toarray()

In [48]:
vectors

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [49]:
vectors[0]

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [50]:
cv.get_feature_names()

D:\Anaconda3\lib\site-packages\sklearn\utils\deprecation.py:87: FutureWarning: Function get_feature_names is deprecated; get_feature_names is deprecated in 1.0 and will be removed in 1.2. Please use get_feature_names_out instead.
  warnings.warn(msg, category=FutureWarning)

['11',
 '15thcenturi',
 '16thcenturi',
 '17thcenturi',
 '18thcenturi',
 '1910',
 '1930',
 '1940',
 '1950',
 '1960',
 '1970',
 '1980',
 '1990',
 '1995',
 '19thcenturi',
 '21stcenturi',
 '3d',
 'abandon',
 'abandonedmin',
 'aborigin',
 'abort',
 'abrahamlincoln',
 'absurd',
 'abus',
 'abusivehusband',
 'acapella',
 'accid',
 'account',
 'acid',
 'action',
 'actionhero',
 'actionheroin',
 'activist',
 'actor',
 'actress',
 'adapt',
 'addict',
 'adolesc',
 'adolfhitl',
 'adopt',
 'adoptedchild',
 'adoptivefath',
 'adoptivemoth',
 'adultanim',
 'adultasachild',
 'adulteri',
 'advanc',
 'adventur',
 'adversari',
 'advertis',
 'advertisingexecut',
 'advertisingexpert',
 'advic',
 'affair',
 'affect',
 'afghanistan',
 'africa',
 'africanamerican',
 'aftercreditssting',
 'afterlif',
 'age',
 'agediffer',
 'agent',
 'aggress',
 'aggressionbyanim',
 'aggressionbypl',
 'agricultur',
 'aid',
 'aircontrol',
 'aircraftcarri',
 'airforc',
 'airplan',
 'airplanecrash',
 'airport',
 'airraid',
 'alabama',
 'alarmclock',
 'alaska',
 'albanian',
 'alcatraz',
 'alcohol',
 'alcoholabus',
 'alcoholicdrink',
 'alcoholicfath',
 'alexanderthegreat',
 'aliceinwonderland',
 'alien',
 'alienabduct',
 'alienattack',
 'aliencontact',
 'alieninfect',
 'alieninvas',
 'alienlife',
 'alienparasit',
 'alienphenomenon',
 'alienplanet',
 'alienrac',
 'alik',
 'allegori',
 'alli',
 'allianc',
 'allig',
 'alon',
 'alp',
 'alterego',
 'alternatedimens',
 'alternatehistori',
 'alternater',
 'alternatetimelin',
 'alternativer',
 'alzheim',
 'alzheimer',
 'amateursocc',
 'amateurtheat',
 'amazon',
 'ambassador',
 'ambiguousend',
 'ambit',
 'ambul',
 'ambush',
 'american',
 'americanabroad',
 'americancivilwar',
 'americandream',
 'americanflag',
 'americanfootbal',
 'americanfootballplay',
 'americanpresid',
 'americanspi',
 'amnesia',
 'amsterdam',
 'amusementpark',
 'anarchiccomedi',
 'anarchist',
 'ancientastronaut',
 'ancientchina',
 'ancientegypt',
 'ancientevil',
 'ancientgreec',
 'ancientrom',
 'ancientworld',
 'android',
 'angel',
 'anger',
 'angrymob',
 'anim',
 'animalattack',
 'animaldeath',
 'animalhorror',
 'animallead',
 'animallov',
 'animalprotect',
 'animalsidekick',
 'animatedsequ',
 'annabel',
 'anonym',
 'anonymouslett',
 'anotherdimens',
 'answeringmachin',
 'ant',
 'antarct',
 'antarctica',
 'antholog',
 'anthropomorph',
 'anti',
 'antidot',
 'antihero',
 'antiquari',
 'antisemit',
 'antisocialpersonalitydisord',
 'antiterror',
 'antiwar',
 'apart',
 'apartheid',
 'apartmentbuild',
 'ape',
 'apocalyps',
 'apocalypt',
 'apostl',
 'appalachia',
 'appl',
 'apprentic',
 'approach',
 'aquarium',
 'aqueduct',
 'arab',
 'arabian',
 'arbitrarylaw',
 'archaeologist',
 'archangelgabriel',
 'archeolog',
 'archeologist',
 'archer',
 'archeri',
 'architect',
 'architectur',
 'arctic',
 'area51',
 'arena',
 'argentina',
 'argument',
 'aristocrat',
 'arizona',
 'arkansa',
 'arkofthecoven',
 'armageddon',
 'armi',
 'armoredcar',
 'armrippedoff',
 'armsdeal',
 'armybas',
 'arrangedmarriag',
 'arrest',
 'arrog',
 'arrow',
 'arson',
 'art',
 'artgalleri',
 'arthous',
 'artifact',
 'artificialinsemin',
 'artificialintellig',
 'artist',
 'arttheft',
 'artthief',
 'asgard',
 'ash',
 'asia',
 'asian',
 'asperger',
 'aspiringactor',
 'aspiringsing',
 'aspiringwrit',
 'assassin',
 'assassinationattempt',
 'assault',
 'assaultrifl',
 'assign',
 'assist',
 'asteroid',
 'asthma',
 'astronaut',
 'asylum',
 'atheist',
 'athlet',
 'atlanta',
 'atlanti',
 'atlanticc',
 'atlanticocean',
 'atomicbomb',
 'atroc',
 'attack',
 'attemptedmurd',
 'attemptedrap',
 'attemptedrobberi',
 'attemptedsuicid',
 'attempttoescap',
 'attic',
 'attract',
 'auction',
 'audienc',
 'audiocassett',
 'audiotap',
 'audit',
 'aunt',
 'auntnephewrelationship',
 'auntniecerelationship',
 'australia',
 'australian',
 'australianaborigin',
 'australianoutback',
 'austria',
 'author',
 'autism',
 'auto',
 'autoaccid',
 'autobiographi',
 'autograph',
 'automobileindustri',
 'automobilerac',
 'autonomi',
 'autoritianeduc',
 'aviat',
 'awkward',
 'awol',
 'ax',
 'axemurd',
 'aynrand',
 'babi',
 'baby',
 'babygenius',
 'babysitt',
 'bachelor',
 'backpack',
 'badboss',
 'badcop',
 'badfather',
 'badluck',
 'badmother',
 'bagdad',
 'bagoverhead',
 'bahama',
 'bailjump',
 'bakeri',
 'balkanwar',
 'ball',
 'ballet',
 'balletdanc',
 'balloon',
 'baltimor',
 'baltimoremaryland',
 'band',
 'bandit',
 'bangkok',
 'banish',
 'bank',
 'banker',
 'bankfraud',
 'bankheist',
 'bankmanag',
 'bankrobb',
 'bankrobberi',
 'bankrupt',
 'bar',
 'barbarian',
 'barbedwir',
 'barcelonaspain',
 'barfight',
 'barn',
 'barricad',
 'barrieric',
 'barrio',
 'barsandrestaur',
 'bartend',
 'basebal',
 'baseballbat',
 'baseballplay',
 'basedonarticl',
 'basedonboardgam',
 'basedoncartoon',
 'basedonchildren',
 'basedoncomicbook',
 'basedoncomicstrip',
 'basedonfairytal',
 'basedonfilm',
 'basedongraphicnovel',
 'basedongreekmyth',
 'basedonnovel',
 'basedonplay',
 'basedonshortfilm',
 'basedonshortstori',
 'basedonstagemus',
 'basedonsupposedlytruestori',
 'basedontoy',
 'basedontrueev',
 'basedontruestori',
 'basedontvseri',
 'basedonvideogam',
 'basedonyoungadultnovel',
 'basement',
 'basketbal',
 'basketballteam',
 'bat',
 'bath',
 'bathhous',
 'bathroomhumor',
 'bathtub',
 'batman',
 'battl',
 'battleassign',
 'battlefield',
 'battleforpow',
 'battleforsurviv',
 'bdsm',
 'beach',
 'beachhous',
 'bear',
 'bearattack',
 'beard',
 'beast',
 'beat',
 'beatnik',
 'beauti',
 'beautifulgirl',
 'beautifulwoman',
 'beautycontest',
 'beautypag',
 'becominganadult',
 'bedandbreakfastplac',
 'bedroom',
 'beer',
 'begnadigung',
 'beguil',
 'behead',
 'behindthescen',
 'beij',
 'belgium',
 'bell',
 'benitomussolini',
 'berlin',
 'berlinwal',
 'bestfriend',
 'bestfriendsinlov',
 'bet',
 'betray',
 'beverlyhil',
 'bhorror',
 'bia',
 'bibl',
 'bicker',
 'bicycl',
 'bigfamili',
 'bigotri',
 'biker',
 'bikini',
 'billard',
 'billionair',
 'billythekid',
 'binocular',
 'biographi',
 'biohazard',
 'biolog',
 'biologicalexperi',
 'biologicalweapon',
 'bipolardisord',
 'bird',
 'birth',
 'birthday',
 'birthdayparti',
 'bisexu',
 'bite',
 'bittersweet',
 'black',
 'blackandwhit',
 'blackandwhitescen',
 'blackandwhitetocolor',
 'blackcat',
 'blackhol',
 'blackhumor',
 'blackmag',
 'blackmail',
 'blackmen',
 'blackop',
 'blackout',
 'blackpanth',
 'blackpeopl',
 'blacksmith',
 'blade',
 'blast',
 'blaxploit',
 'blind',
 'blinddat',
 'blindnessandimpairedvis',
 'blizzard',
 'blog',
 'blond',
 'blood',
 'bloodonshirt',
 'bloodsampl',
 'bloodsplatt',
 'bloodspurt',
 'bloodsuck',
 'blowjob',
 'blue',
 'blueprint',
 'blunt',
 'bmovi',
 'boardinghous',
 'boardingschool',
 'boat',
 'boataccid',
 'boatchas',
 'bodilydisabledperson',
 'body',
 'bodyexchang',
 'bodyguard',
 'bodyhorror',
 'bollywood',
 'bomb',
 'bombattack',
 'bomber',
 'bombplant',
 'bombsquad',
 'bondag',
 'bone',
 'bonfir',
 'bong',
 'boobytrap',
 'book',
 'bookeditor',
 'bookofthedead',
 'bookshop',
 'bookstor',
 'bootlegg',
 'border',
 'boredom',
 'bosnianwarof1992',
 'boss',
 'boston',
 'botanist',
 'bounti',
 'bountyhunt',
 'bourgeoisi',
 'bowandarrow',
 'bowl',
 'bowlingbal',
 'bowlingteam',
 'box',
 'boxer',
 'boxingmatch',
 'boxingtrain',
 'boy',
 'boyfriend',
 'boyfriendex',
 'boyfriendgirlfriendrelationship',
 'boygeniu',
 'boys',
 'brain',
 'braintumor',
 'brainwash',
 'bratislava',
 'braveri',
 'brawl',
 'brazil',
 'brazilian',
 'break',
 'breakdanc',
 'breakingthefourthwal',
 'breast',
 'bride',
 'bridegroom',
 'bridesmaid',
 'bridg',
 'brief',
 'briefcas',
 'brighton',
 'britain',
 'british',
 'britisharmi',
 'britishempir',
 'britishsecretservic',
 'britishsoldi',
 'broadway',
 'brokenarm',
 'brokenengag',
 'brokenneck',
 'broker',
 'bromanc',
 'bronx',
 'brood',
 'brooklynnewyorkc',
 'broom',
 'broth',
 'brothel',
 'brother',
 'brotheragainstbroth',
 'brotherbrotherrelationship',
 'brothersisterincest',
 'brothersisterrelationship',
 'brumbi',
 'brutal',
 'bu',
 'bucketlist',
 'budapest',
 'buddhism',
 'buddhistmonk',
 'buddi',
 'buddycomedi',
 'buddycop',
 'budget',
 'bullet',
 'bulletwound',
 'bulli',
 'bum',
 'bungee',
 'bunker',
 'bunni',
 'bureaucraci',
 'burglar',
 'burglari',
 'buriedal',
 'burn',
 'burnedal',
 'burningofwitch',
 'burnvictim',
 'bush',
 'busi',
 'businesseth',
 'businessman',
 'businessstart',
 'businesswoman',
 'busrid',
 'butcher',
 'butler',
 'butterfli',
 'button',
 'cabin',
 'cabininthewood',
 'cage',
 'cairo',
 'california',
 'callboy',
 'callgirl',
 'calypso',
 'cambodia',
 'camcord',
 'camelot',
 'camera',
 'camp',
 'campaign',
 'campfir',
 'campu',
 'canada',
 'cancer',
 'candi',
 'candl',
 'candlelightvigil',
 'cannabi',
 'cannib',
 'cano',
 'canon',
 'canuxploit',
 'canyon',
 'caper',
 'capit',
 'captain',
 'captainamerica',
 'captainnemo',
 'captiv',
 'captur',
 'car',
 'caraccid',
 'carbomb',
 'carbreakdown',
 'carchas',
 'carcrash',
 'cardeal',
 'cardgam',
 'career',
 'careerwoman',
 'carefre',
 'caregiv',
 'caretak',
 'carexplos',
 'cargoship',
 'caribbean',
 'carjack',
 'carjourney',
 'carmechan',
 'carmovi',
 'carni',
 'carniv',
 'carnivorouspl',
 'carpet',
 'carrac',
 'carrierpigeon',
 'carsetonfir',
 'cartoon',
 'cartooncat',
 'casanova',
 'case',
 'casino',
 'castl',
 'castrat',
 'casualsex',
 'cat',
 'cataclysm',
 'catandmous',
 'catastroph',
 'catfish',
 'cathedr',
 'cathol',
 'catholic',
 'catholicchurch',
 'catholicpriest',
 'catholicschool',
 'cattl',
 'cattledr',
 'catwoman',
 'cavalri',
 'cave',
 'cavemen',
 'celebr',
 'celibaci',
 'cello',
 'cellphon',
 'cemetari',
 'cemeteri',
 'centralamerica',
 'centralandsouthamerica',
 'centralpark',
 'ceremoni',
 'cgi',
 'chain',
 'chainsaw',
 'chambersofabarrist',
 'champion',
 'championship',
 'chanc',
 'chang',
 'changingthepastorfutur',
 'chao',
 'chaosandmayham',
 'chaostheori',
 'chapel',
 'chariot',
 'chariti',
 'charlesdicken',
 'chase',
 'chasesandrac',
 'chauffeur',
 'cheat',
 'cheatinghusband',
 'cheatingonpartn',
 'cheatingwif',
 'cheerlead',
 'chef',
 'chemic',
 'chicago',
 'chicken',
 'chief',
 'child',
 'childabus',
 'childasanadult',
 'childbrid',
 'childcustodi',
 'childhero',
 'childhoodfriend',
 'childhoodmemori',
 'childhoodsexualabus',
 'childhoodtrauma',
 'childlabor',
 'childlabour',
 'childless',
 'childmurd',
 'childmurder',
 'childofdivorc',
 'childprodigi',
 'children',
 'childvampir',
 'chile',
 'chimp',
 'chimpanze',
 'china',
 'chinatown',
 'chines',
 'chipmunk',
 'chivalri',
 'chocol',
 'choir',
 'cholera',
 'cholo',
 'chorusgirl',
 'chosenon',
 'christ',
 'christian',
 'christianfilm',
 'christma',
 'christmascarol',
 'christmasev',
 'christmasparti',
 'christmastre',
 'church',
 'churchchoir',
 'churchservic',
 'cia',
 'ciaagent',
 'cigarett',
 'cigarettelight',
 'cigarettesmok',
 'cigarsmok',
 'cinderella',
 'cinema',
 'circu',
 'citi',
 'cityruin',
 'civilright',
 'civilrightsmov',
 'civilwar',
 'clairvoy',
 'class',
 'classdiffer',
 'classic',
 'classicalmus',
 'classifi',
 'classmat',
 'classprejudic',
 'classroom',
 'classsocieti',
 'claustrophobia',
 'clerk',
 'clever',
 'cliff',
 'climat',
 'climatechang',
 'climb',
 'cliqu',
 'clock',
 'clocktow',
 'clone',
 'clown',
 'club',
 'clumsi',
 'clumsyfellow',
 'coach',
 'coalmin',
 'coastguard',
 'cobra',
 'cocain',
 'cockneyacc',
 'cockroach',
 'cocktail',
 'cod',
 'code',
 'coffeeshop',
 'coffin',
 'cohabit',
 'coldwar',
 'coleyoung',
 'collector',
 'colleg',
 'collegestud',
 'colombia',
 'colonel',
 'coloni',
 'colorado',
 'columbin',
 'coma',
 'comb',
 'combat',
 'combov',
 'comeback',
 'comedi',
 'comedian',
 'comet',
 'comicbook',
 'comingofag',
 'comingout',
 'command',
 'commando',
 'commandounit',
 'commerci',
 'commit',
 'commun',
 'compani',
 'compass',
 'competit',
 'compos',
 'compulsivegambl',
 'comput',
 'computeranim',
 'computerexpert',
 'computerhack',
 'computerprogram',
 'computerviru',
 'conartist',
 'concentrationcamp',
 'concert',
 'concili',
 'condom',
 'conductor',
 'confeder',
 'confederatesoldi',
 'confess',
 'confid',
 'congress',
 'conman',
 'consandscam',
 'conscienc',
 'conscious',
 'conserv',
 'conspiraci',
 'conspiracyofmurd',
 'conspiracytheori',
 'contamin',
 'contest',
 'contractkil',
 'control',
 'controversi',
 'conveniencestor',
 'convent',
 'convers',
 'convert',
 'conveyorbelt',
 'convict',
 'convoy',
 'cook',
 'cookbook',
 'cop',
 'copenhagen',
 'coralreef',
 'coron',
 'corpor',
 'corporatecrim',
 'corps',
 'corrupt',
 'corruptcop',
 'corruptpolitician',
 'costum',
 'countdown',
 'countess',
 'countryclub',
 'countryest',
 'countryhous',
 'countrylif',
 'countrymus',
 'countrysid',
 'coup',
 'coupd',
 'coupl',
 'courag',
 'court',
 'courtcas',
 'courthous',
 'courtroom',
 'courtship',
 'cover',
 'coveredinvestig',
 'covertoper',
 'cow',
 'coward',
 'cowardic',
 'cowardli',
 'cowboy',
 'crab',
 'crash',
 'crashland',
 'crazi',
 'creation',
 'creativ',
 'creatur',
 'crew',
 'cri',
 'crime',
 'crimeboss',
 'crimefamili',
 'crimefight',
 'crimelord',
 'crimin',
 'criminalhero',
 'criminalmastermind',
 'criminalunderworld',
 'crisi',
 'crisisoffaith',
 'critic',
 'criticismandblam',
 'crocodil',
 'crook',
 'crookedlawy',
 'cropcircl',
 'cross',
 'crosscountri',
 'crossdress',
 'crosswordpuzzl',
 'crucifix',
 'crucifixion',
 'crudehumor',
 'cruelti',
 'cruis',
 'cruiseship',
 'crusad',
 'crush',
 'cryingwoman',
 'cryogen',
 'cuba',
 'cult',
 'cultclass',
 'cultdirector',
 'cultfavorit',
 'cultfigur',
 'cultfilm',
 'cultlead',
 'cultur',
 'culturaldiffer',
 'cultureclash',
 'cupboard',
 'cure',
 'curios',
 'current',
 'curs',
 'custodybattl',
 'cut',
 'cuttingthecord',
 'cyberpunk',
 'cyberterror',
 'cyborg',
 'cyclop',
 'cynic',
 'dagger',
 'dailylif',
 'dalailama',
 'dallastexa',
 'dam',
 'damselindistress',
 'danc',
 'dancecontest',
 'dancer',
 'danceteach',
 'dancingmast',
 'dancingscen',
 ...]

In [51]:
['loved', 'loving', 'love']
['love', 'love', 'love']

['love', 'love', 'love']

In [52]:
ps.stem('danced')

'danc'

In [53]:
from sklearn.metrics.pairwise import cosine_similarity

In [54]:
similarity = cosine_similarity(vectors)

In [55]:
sorted(list(enumerate(similarity[0])), reverse=True, key=lambda x:x[1])[1:6]

[(47, 0.29095718698132317),
 (1290, 0.25197631533948484),
 (492, 0.2182178902359924),
 (2659, 0.2182178902359924),
 (61, 0.19518001458970663)]

In [56]:
def recommend(movie):
    movie_index = new_df[new_df['title'] == movie].index[0]
    distances = similarity[movie_index]
    movies_list = sorted(list(enumerate(distances)), reverse=True, key=lambda x:x[1])[1:6]
    
    for i in movies_list:
        print(new_df.iloc[i[0]].title)

In [57]:
recommend('Batman Begins')

The Dark Knight
Batman v Superman: Dawn of Justice
Batman & Robin
Batman
Batman

In [58]:
new_df.iloc[1148].title

'The Sixth Sense'

In [59]:
import pickle

In [60]:
pickle.dump(new_df, open('movies.pkl', 'wb'))

In [61]:
new_df['title'].values

array(['Avatar', "Pirates of the Caribbean: At World's End", 'Spectre',
       ..., 'Signed, Sealed, Delivered', 'Shanghai Calling',
       'My Date with Drew'], dtype=object)

In [62]:
pickle.dump(new_df.to_dict(), open('movie_dict.pkl', 'wb'))

In [63]:
pickle.dump(similarity, open('similarity.pkl', 'wb'))